title: Keelboat
description: shipshape library demonstration
theme: jekyll-theme-cayman
baseurl: "/keelboat"
url: "https://shipshape-marine.github.io"

# Build settings
markdown: kramdown

# Include additional directories for GitHub Pages
include:
  - renders
  - downloads
  - lines

# Project metadata
project:
  coordinator: "A/Prof Martin Henz"
  institution: "School of Computing, National University of Singapore"
  email: "henz@nus.edu.sg"
